FROM node:16.20.1

RUN mkdir /app
WORKDIR /app

# docker build -t yarn .
# docker run -it --rm --volume ${PWD}:/home node:16.20.1 bash

# you cn run docker container inside the folder with SPA-app
# docker run -it --rm --publish '8090:8090' --volume ${PWD}:/app yarn bash
# docker run -it --rm --publish '8090:8090' --volume ${PWD}:/app yarn yarn start
# alias
# alias my_yarn="docker run -it --rm --publish '8090:8090' --volume ${PWD}:/app yarn yarn"
