FROM debian:latest

RUN apt update && apt install -y chocolate-doom

CMD /usr/games/doom

# docker build -t doom .

# docker run -it -e DISPLAY="${IP}:0" doom bash
# docker run -e DISPLAY="${IP}:0" doom /usr/games/doom
